version: '3'
services:
  node-express-app:
    build: .
    ports:
      - 3100:3000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - port=3000
      - NODE_ENV=production