version: '3'
services:
  node-express-app:
    build: .
    ports:
      - 3100:3000
    environment:
      - port=3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: